### PR TITLE
Support complex schemas with UNION

### PR DESCRIPTION
**Pull request by AlexSvyatets**
1. Fix issue with supporting Enum
2. Support complex schemas with UNION

### CODE REVIEW

**Comment by AlexSvyatets** [comment]
Hi @jwills !
Can you check this PR. I have pushed it on Jul, 2018 and it was not reviewed till now.

**Comment by jwills** [comment]
Ack, horrible that I missed this-- will merge it now. Thank you!

**Comment by AlexSvyatets** [comment]
@jwills 
So can it be released as new version of com.cloudera.science:avro-json?

**Comment by jwills** [comment]
Sure, send me a PR?

**Comment by AlexSvyatets** [comment]
> 
> 
> Sure, send me a PR?

@jwills !
I don't understand what you need

**Pull request merged**
